# Site settings
title: RTL & Verification Notes
description: '안녕하세요 해당 블로그는 RTL에 관한 설계와 검증에 관련된 블로그입니다.' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://github.com/chemistrykr/WonhoChang" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/theme.svg"
logo-icon: "/assets/img/branding/main_semi.svg"
logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/MVM-logo-full-dark.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Wonho Chang # add your name
author-pic: Myself_Neon_grey.jpg
about-author:  |
  안녕하세요, RTL Design/Verification Engineer입니다.<br>
  Systemverilog 및 UVM 검증에 관련된 지식을 정리하기 위해 블로그를 시작하였습니다. 
  아직 현업에서 저연차로 부족한 점이 많다는 것을 이해해주시고 포스팅 내용을 확인해 주시면 감사하겠습니다.<br> 
  RTL 관련 내용뿐만 아니라 부족하지만 Computer Architecture or DRAM Knowledge에 관한 내용도 정리하도록 하겠습니다

# Contact links
email: chemistrykr@naver.com # Add your Email address
phone: # Add your Phone number
website: https://amaynez.github.io # Add your website
linkedin: amaynez # Add your Linkedin handle
github: amaynez # Add your Github handle
twitter: '@MvmThe' # Add your Twitter handle
bandcamp: armandomaynez # Add your Bandcamp username
stackoverflow: stackoverflow # Add your stackoverflow account

# Newsletter
mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Tracker
analytics: G-R8SZS2YBZK
fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: # The GitHub repo URL.  https://utteranc.es/
  issue_term: # The GitHub issue label
  label: # The GitHub comments label
  theme: # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]